apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmicsec.fullname" . }}-config
  labels:
    {{- include "cosmicsec.labels" . | nindent 4 }}
data:
  ENVIRONMENT: "production"
  PLATFORM_RUNTIME_MODE: "hybrid"
  POSTGRES_HOST: "{{ include "cosmicsec.fullname" . }}-postgresql"
  REDIS_HOST: "{{ include "cosmicsec.fullname" . }}-redis-master"
