# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import ingest_pb2 as ingest__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ingest_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IngestServiceStub:
    """---------------------------------------------------------------------------
    IngestService — primary gRPC interface for the Rust ingest engine
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestBatch = channel.unary_unary(
            "/cosmicsec.ingest.v1.IngestService/IngestBatch",
            request_serializer=ingest__pb2.IngestRequest.SerializeToString,
            response_deserializer=ingest__pb2.IngestResponse.FromString,
            _registered_method=True,
        )
        self.StreamIngest = channel.unary_stream(
            "/cosmicsec.ingest.v1.IngestService/StreamIngest",
            request_serializer=ingest__pb2.IngestRequest.SerializeToString,
            response_deserializer=ingest__pb2.FindingProto.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/cosmicsec.ingest.v1.IngestService/GetStatus",
            request_serializer=ingest__pb2.StatusRequest.SerializeToString,
            response_deserializer=ingest__pb2.StatusResponse.FromString,
            _registered_method=True,
        )


class IngestServiceServicer:
    """---------------------------------------------------------------------------
    IngestService — primary gRPC interface for the Rust ingest engine
    ---------------------------------------------------------------------------

    """

    def IngestBatch(self, request, context):
        """Submit a batch of raw scan-tool output for parsing and storage."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamIngest(self, request, context):
        """Stream findings back to caller as they are parsed (server-side streaming)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Return engine health and throughput metrics."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IngestBatch": grpc.unary_unary_rpc_method_handler(
            servicer.IngestBatch,
            request_deserializer=ingest__pb2.IngestRequest.FromString,
            response_serializer=ingest__pb2.IngestResponse.SerializeToString,
        ),
        "StreamIngest": grpc.unary_stream_rpc_method_handler(
            servicer.StreamIngest,
            request_deserializer=ingest__pb2.IngestRequest.FromString,
            response_serializer=ingest__pb2.FindingProto.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=ingest__pb2.StatusRequest.FromString,
            response_serializer=ingest__pb2.StatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cosmicsec.ingest.v1.IngestService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("cosmicsec.ingest.v1.IngestService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class IngestService:
    """---------------------------------------------------------------------------
    IngestService — primary gRPC interface for the Rust ingest engine
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def IngestBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cosmicsec.ingest.v1.IngestService/IngestBatch",
            ingest__pb2.IngestRequest.SerializeToString,
            ingest__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamIngest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/cosmicsec.ingest.v1.IngestService/StreamIngest",
            ingest__pb2.IngestRequest.SerializeToString,
            ingest__pb2.FindingProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cosmicsec.ingest.v1.IngestService/GetStatus",
            ingest__pb2.StatusRequest.SerializeToString,
            ingest__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
